# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: openstack-gpu-runner
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_4xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    # Path of the relevant workflow file
    labels:
      - cirun-openstack-gpu

  - name: openstack-cpu-runner
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_medium
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    # Path of the relevant workflow file
    labels:
      - cirun-cpu-runner
