# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: openstack-runner
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: m1.small
    # The machine image to use for creating VM
    machine_image: ubuntu-2004-cloud-focal-20221021
    # Path of the relevant workflow file
    labels:
      - cirun-openstack
