# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: openstack-runner
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: OT-GPU-1
    # The machine image to use for creating VM
    machine_image: Ubuntu 20.04 Focal Server with NVIDIA
    # Path of the relevant workflow file
    workflow: .github/workflows/blank.yml
