name: Cirun on OpenStack [CPU]

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [1, 2]
    runs-on: cirun-cpu-runner
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run "df -h"
        run: df -h

      - name: Run "uptime"
        run: uptime
        
      - name: Run "lscpu"
        run: lscpu

      - name: Run "nproc"
        run: nproc

      - name: Run "lspci"
        run: lspci

      - name: Try nvidia-smi
        run: nvidia-smi || true

      - name: Check distribution
        run: cat /etc/*release

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          python-version: 3.8
          miniconda-version: "latest"
