name: Cirun on OpenStack [GPU]

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [1, 2, 3, 4]
    runs-on: cirun-openstack-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run "df -h"
        run: df -h

      - name: Run "uptime"
        run: uptime
        
      - name: Run "lscpu"
        run: lscpu

      - name: Run "nproc"
        run: nproc

      - name: Run "lspci"
        run: lspci

      - name: Try nvidia-smi
        run: nvidia-smi || true

      - name: Try Docker
        run: |
          docker ps
          docker version
      - name: Docker run GPU container
        run: |
          docker run --gpus all --rm nvcr.io/nvidia/pytorch:21.02-py3 nvidia-smi
      - name: Check Docker MTU value
        run: |
          cat /etc/docker/daemon.json || true
      - name: Check distribution
        run: cat /etc/*release

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          python-version: 3.11
          miniconda-version: "latest"
      - name: Sleep
        run: sleep 10
